[package]
name = "neond00m/axis"
version = "0.2.3"
description = "An agnostic, simple and versatile input library for ECS. "
keywords = ["input", "ecs",]
authors = ["NeonD00m", "as8d"]
license = "MIT"

realm = "shared"

registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Neond00m/Axis"

# for some reason include = ["src"} doesn't work
exclude = ["zune", "tests", "pesde.lock", "pesde.toml", "lune_packages", "luau_packages", "moonwave.toml", "pages", "examples", "images", "luau-lsp", "exampleGame", "example.project.json", "docs", "globalTypes.d.luau"]
